// AUTO-GENERATED by sync-products.js — do not edit manually
export const PRODUCTS = {
	"69b246101f9e58": {
		"name": "Pink Women’s basic softstyle t-shirt HMC Crow",
		"variants": {
			"S": {
				"price": 2000,
				"printful_variant_id": 5230267413
			},
			"M": {
				"price": 2000,
				"printful_variant_id": 5230267414
			},
			"L": {
				"price": 2000,
				"printful_variant_id": 5230267415
			},
			"XL": {
				"price": 2000,
				"printful_variant_id": 5230267416
			},
			"2XL": {
				"price": 2000,
				"printful_variant_id": 5230267417
			}
		}
	},
	"69b2f6abe68db2": {
		"name": "Black Unisex t-shirt HMC Crow",
		"variants": {
			"XS": {
				"price": 2000,
				"printful_variant_id": 5230773689
			},
			"S": {
				"price": 2000,
				"printful_variant_id": 5230773690
			},
			"M": {
				"price": 2000,
				"printful_variant_id": 5230773691
			},
			"L": {
				"price": 2000,
				"printful_variant_id": 5230773692
			},
			"XL": {
				"price": 2000,
				"printful_variant_id": 5230773693
			},
			"2XL": {
				"price": 2000,
				"printful_variant_id": 5230773694
			}
		}
	},
	"69af06d5cf6119": {
		"name": "Unisex Staple Eco T-Shirt HMC Crow",
		"variants": {
			"XS": {
				"price": 2000,
				"printful_variant_id": 5226945173
			},
			"S": {
				"price": 2000,
				"printful_variant_id": 5226945174
			},
			"M": {
				"price": 2000,
				"printful_variant_id": 5226945175
			},
			"L": {
				"price": 2000,
				"printful_variant_id": 5226945176
			},
			"XL": {
				"price": 2000,
				"printful_variant_id": 5226945177
			},
			"2XL": {
				"price": 2000,
				"printful_variant_id": 5226945178
			},
			"3XL": {
				"price": 2000,
				"printful_variant_id": 5226945179
			}
		}
	},
	"69b05922051f48": {
		"name": "Women’s basic softstyle t-shirt HMC Crow",
		"variants": {
			"S": {
				"price": 2000,
				"printful_variant_id": 5228085838
			},
			"M": {
				"price": 2000,
				"printful_variant_id": 5228085839
			},
			"L": {
				"price": 2000,
				"printful_variant_id": 5228085840
			},
			"XL": {
				"price": 2000,
				"printful_variant_id": 5228085841
			},
			"2XL": {
				"price": 2000,
				"printful_variant_id": 5228085842
			}
		}
	},
	"69b05a6edf8004": {
		"name": "Women's Relaxed T-Shirt HMC Crow",
		"variants": {
			"S": {
				"price": 2000,
				"printful_variant_id": 5228091165
			},
			"M": {
				"price": 2000,
				"printful_variant_id": 5228091166
			},
			"L": {
				"price": 2000,
				"printful_variant_id": 5228091167
			},
			"XL": {
				"price": 2000,
				"printful_variant_id": 5228091169
			},
			"2XL": {
				"price": 2000,
				"printful_variant_id": 5228091171
			},
			"3XL": {
				"price": 2000,
				"printful_variant_id": 5228091172
			}
		}
	}
};
