// AUTO-GENERATED by sync-products.js — do not edit manually
export const PRODUCTS = {
	"69e05ba02a2e08": {
		"name": "Women’s Basic Softstyle T-Shirt HMC Crow Front Only",
		"price": 2000,
		"variants": {
			"White": {
				"S": {
					"printful_variant_id": 5270106363
				},
				"M": {
					"printful_variant_id": 5270106364
				},
				"L": {
					"printful_variant_id": 5270106365
				},
				"XL": {
					"printful_variant_id": 5270106366
				},
				"2XL": {
					"printful_variant_id": 5270106367
				}
			},
			"Red": {
				"S": {
					"printful_variant_id": 5270106343
				},
				"M": {
					"printful_variant_id": 5270106344
				},
				"L": {
					"printful_variant_id": 5270106345
				},
				"XL": {
					"printful_variant_id": 5270106346
				},
				"2XL": {
					"printful_variant_id": 5270106347
				}
			},
			"Azalea": {
				"S": {
					"printful_variant_id": 5270106358
				},
				"M": {
					"printful_variant_id": 5270106359
				},
				"L": {
					"printful_variant_id": 5270106360
				},
				"XL": {
					"printful_variant_id": 5270106361
				},
				"2XL": {
					"printful_variant_id": 5270106362
				}
			},
			"Irish Green": {
				"S": {
					"printful_variant_id": 5270106353
				},
				"M": {
					"printful_variant_id": 5270106354
				},
				"L": {
					"printful_variant_id": 5270106355
				},
				"XL": {
					"printful_variant_id": 5270106356
				},
				"2XL": {
					"printful_variant_id": 5270106357
				}
			},
			"Navy": {
				"S": {
					"printful_variant_id": 5270106338
				},
				"M": {
					"printful_variant_id": 5270106339
				},
				"L": {
					"printful_variant_id": 5270106340
				},
				"XL": {
					"printful_variant_id": 5270106341
				},
				"2XL": {
					"printful_variant_id": 5270106342
				}
			},
			"Royal": {
				"S": {
					"printful_variant_id": 5270106348
				},
				"M": {
					"printful_variant_id": 5270106349
				},
				"L": {
					"printful_variant_id": 5270106350
				},
				"XL": {
					"printful_variant_id": 5270106351
				},
				"2XL": {
					"printful_variant_id": 5270106352
				}
			},
			"Black": {
				"S": {
					"printful_variant_id": 5270106333
				},
				"M": {
					"printful_variant_id": 5270106334
				},
				"L": {
					"printful_variant_id": 5270106335
				},
				"XL": {
					"printful_variant_id": 5270106336
				},
				"2XL": {
					"printful_variant_id": 5270106337
				}
			}
		}
	},
	"69e056a4a75bc4": {
		"name": "Women's Relaxed T-Shirt HMC Crow Front Only",
		"price": 2000,
		"variants": {
			"White": {
				"S": {
					"printful_variant_id": 5270096296
				},
				"M": {
					"printful_variant_id": 5270096297
				},
				"L": {
					"printful_variant_id": 5270096298
				},
				"XL": {
					"printful_variant_id": 5270096299
				},
				"2XL": {
					"printful_variant_id": 5270096300
				},
				"3XL": {
					"printful_variant_id": 5270096301
				}
			},
			"Heather Red": {
				"S": {
					"printful_variant_id": 5270096278
				},
				"M": {
					"printful_variant_id": 5270096279
				},
				"L": {
					"printful_variant_id": 5270096280
				},
				"XL": {
					"printful_variant_id": 5270096281
				},
				"2XL": {
					"printful_variant_id": 5270096282
				},
				"3XL": {
					"printful_variant_id": 5270096283
				}
			},
			"Maroon": {
				"S": {
					"printful_variant_id": 5270096254
				},
				"M": {
					"printful_variant_id": 5270096255
				},
				"L": {
					"printful_variant_id": 5270096256
				},
				"XL": {
					"printful_variant_id": 5270096257
				},
				"2XL": {
					"printful_variant_id": 5270096258
				},
				"3XL": {
					"printful_variant_id": 5270096259
				}
			},
			"Pink": {
				"S": {
					"printful_variant_id": 5270096290
				},
				"M": {
					"printful_variant_id": 5270096291
				},
				"L": {
					"printful_variant_id": 5270096292
				},
				"XL": {
					"printful_variant_id": 5270096293
				},
				"2XL": {
					"printful_variant_id": 5270096294
				},
				"3XL": {
					"printful_variant_id": 5270096295
				}
			},
			"Forest Green": {
				"S": {
					"printful_variant_id": 5270096260
				},
				"M": {
					"printful_variant_id": 5270096261
				},
				"L": {
					"printful_variant_id": 5270096262
				},
				"XL": {
					"printful_variant_id": 5270096263
				},
				"2XL": {
					"printful_variant_id": 5270096264
				},
				"3XL": {
					"printful_variant_id": 5270096265
				}
			},
			"Leaf": {
				"S": {
					"printful_variant_id": 5270096284
				},
				"M": {
					"printful_variant_id": 5270096285
				},
				"L": {
					"printful_variant_id": 5270096286
				},
				"XL": {
					"printful_variant_id": 5270096287
				},
				"2XL": {
					"printful_variant_id": 5270096288
				},
				"3XL": {
					"printful_variant_id": 5270096289
				}
			},
			"Heather Deep Teal": {
				"S": {
					"printful_variant_id": 5270096266
				},
				"M": {
					"printful_variant_id": 5270096267
				},
				"L": {
					"printful_variant_id": 5270096268
				},
				"XL": {
					"printful_variant_id": 5270096269
				},
				"2XL": {
					"printful_variant_id": 5270096270
				},
				"3XL": {
					"printful_variant_id": 5270096271
				}
			},
			"Navy": {
				"S": {
					"printful_variant_id": 5270096242
				},
				"M": {
					"printful_variant_id": 5270096243
				},
				"L": {
					"printful_variant_id": 5270096244
				},
				"XL": {
					"printful_variant_id": 5270096245
				},
				"2XL": {
					"printful_variant_id": 5270096246
				},
				"3XL": {
					"printful_variant_id": 5270096247
				}
			},
			"Heather True Royal": {
				"S": {
					"printful_variant_id": 5270096272
				},
				"M": {
					"printful_variant_id": 5270096273
				},
				"L": {
					"printful_variant_id": 5270096274
				},
				"XL": {
					"printful_variant_id": 5270096275
				},
				"2XL": {
					"printful_variant_id": 5270096276
				},
				"3XL": {
					"printful_variant_id": 5270096277
				}
			},
			"Black": {
				"S": {
					"printful_variant_id": 5270096248
				},
				"M": {
					"printful_variant_id": 5270096249
				},
				"L": {
					"printful_variant_id": 5270096250
				},
				"XL": {
					"printful_variant_id": 5270096251
				},
				"2XL": {
					"printful_variant_id": 5270096252
				},
				"3XL": {
					"printful_variant_id": 5270096253
				}
			}
		}
	},
	"69e056aba0e644": {
		"name": "Unisex T-Shirt HMC Crow Front Only",
		"price": 2000,
		"variants": {
			"White": {
				"XS": {
					"printful_variant_id": 5270096433
				},
				"S": {
					"printful_variant_id": 5270096434
				},
				"M": {
					"printful_variant_id": 5270096435
				},
				"L": {
					"printful_variant_id": 5270096436
				},
				"XL": {
					"printful_variant_id": 5270096437
				},
				"2XL": {
					"printful_variant_id": 5270096438
				}
			},
			"Cardinal": {
				"XS": {
					"printful_variant_id": 5270096400
				},
				"S": {
					"printful_variant_id": 5270096401
				},
				"M": {
					"printful_variant_id": 5270096402
				},
				"L": {
					"printful_variant_id": 5270096403
				},
				"XL": {
					"printful_variant_id": 5270096404
				},
				"2XL": {
					"printful_variant_id": 5270096405
				}
			},
			"Pink": {
				"S": {
					"printful_variant_id": 5270096428
				},
				"M": {
					"printful_variant_id": 5270096429
				},
				"L": {
					"printful_variant_id": 5270096430
				},
				"XL": {
					"printful_variant_id": 5270096431
				},
				"2XL": {
					"printful_variant_id": 5270096432
				}
			},
			"Mustard": {
				"XS": {
					"printful_variant_id": 5270096416
				},
				"S": {
					"printful_variant_id": 5270096417
				},
				"M": {
					"printful_variant_id": 5270096418
				},
				"L": {
					"printful_variant_id": 5270096419
				},
				"XL": {
					"printful_variant_id": 5270096420
				},
				"2XL": {
					"printful_variant_id": 5270096421
				}
			},
			"Forest": {
				"S": {
					"printful_variant_id": 5270096406
				},
				"M": {
					"printful_variant_id": 5270096407
				},
				"L": {
					"printful_variant_id": 5270096408
				},
				"XL": {
					"printful_variant_id": 5270096409
				},
				"2XL": {
					"printful_variant_id": 5270096410
				}
			},
			"Teal": {
				"XS": {
					"printful_variant_id": 5270096422
				},
				"S": {
					"printful_variant_id": 5270096423
				},
				"M": {
					"printful_variant_id": 5270096424
				},
				"L": {
					"printful_variant_id": 5270096425
				},
				"XL": {
					"printful_variant_id": 5270096426
				},
				"2XL": {
					"printful_variant_id": 5270096427
				}
			},
			"Aqua": {
				"S": {
					"printful_variant_id": 5270096411
				},
				"M": {
					"printful_variant_id": 5270096412
				},
				"L": {
					"printful_variant_id": 5270096413
				},
				"XL": {
					"printful_variant_id": 5270096414
				},
				"2XL": {
					"printful_variant_id": 5270096415
				}
			},
			"Navy": {
				"XS": {
					"printful_variant_id": 5270096394
				},
				"S": {
					"printful_variant_id": 5270096395
				},
				"M": {
					"printful_variant_id": 5270096396
				},
				"L": {
					"printful_variant_id": 5270096397
				},
				"XL": {
					"printful_variant_id": 5270096398
				},
				"2XL": {
					"printful_variant_id": 5270096399
				}
			},
			"Vintage Black": {
				"XS": {
					"printful_variant_id": 5270096388
				},
				"S": {
					"printful_variant_id": 5270096389
				},
				"M": {
					"printful_variant_id": 5270096390
				},
				"L": {
					"printful_variant_id": 5270096391
				},
				"XL": {
					"printful_variant_id": 5270096392
				},
				"2XL": {
					"printful_variant_id": 5270096393
				}
			}
		}
	},
	"69e05ba41a5e83": {
		"name": "Women’s Basic Softstyle T-Shirt HMC Crow Front and Back",
		"price": 2000,
		"variants": {
			"White": {
				"S": {
					"printful_variant_id": 5270106533
				},
				"M": {
					"printful_variant_id": 5270106534
				},
				"L": {
					"printful_variant_id": 5270106536
				},
				"XL": {
					"printful_variant_id": 5270106537
				},
				"2XL": {
					"printful_variant_id": 5270106539
				}
			},
			"Red": {
				"S": {
					"printful_variant_id": 5270106505
				},
				"M": {
					"printful_variant_id": 5270106506
				},
				"L": {
					"printful_variant_id": 5270106507
				},
				"XL": {
					"printful_variant_id": 5270106509
				},
				"2XL": {
					"printful_variant_id": 5270106510
				}
			},
			"Azalea": {
				"S": {
					"printful_variant_id": 5270106526
				},
				"M": {
					"printful_variant_id": 5270106528
				},
				"L": {
					"printful_variant_id": 5270106529
				},
				"XL": {
					"printful_variant_id": 5270106530
				},
				"2XL": {
					"printful_variant_id": 5270106532
				}
			},
			"Irish Green": {
				"S": {
					"printful_variant_id": 5270106519
				},
				"M": {
					"printful_variant_id": 5270106520
				},
				"L": {
					"printful_variant_id": 5270106522
				},
				"XL": {
					"printful_variant_id": 5270106523
				},
				"2XL": {
					"printful_variant_id": 5270106525
				}
			},
			"Navy": {
				"S": {
					"printful_variant_id": 5270106497
				},
				"M": {
					"printful_variant_id": 5270106499
				},
				"L": {
					"printful_variant_id": 5270106500
				},
				"XL": {
					"printful_variant_id": 5270106502
				},
				"2XL": {
					"printful_variant_id": 5270106503
				}
			},
			"Royal": {
				"S": {
					"printful_variant_id": 5270106511
				},
				"M": {
					"printful_variant_id": 5270106513
				},
				"L": {
					"printful_variant_id": 5270106514
				},
				"XL": {
					"printful_variant_id": 5270106516
				},
				"2XL": {
					"printful_variant_id": 5270106518
				}
			},
			"Black": {
				"S": {
					"printful_variant_id": 5270106489
				},
				"M": {
					"printful_variant_id": 5270106491
				},
				"L": {
					"printful_variant_id": 5270106492
				},
				"XL": {
					"printful_variant_id": 5270106494
				},
				"2XL": {
					"printful_variant_id": 5270106495
				}
			}
		}
	},
	"69e056a85ac3c9": {
		"name": "Women's Relaxed T-Shirt HMC Crow Front And Back",
		"price": 2000,
		"variants": {
			"White": {
				"S": {
					"printful_variant_id": 5270096367
				},
				"M": {
					"printful_variant_id": 5270096368
				},
				"L": {
					"printful_variant_id": 5270096369
				},
				"XL": {
					"printful_variant_id": 5270096370
				},
				"2XL": {
					"printful_variant_id": 5270096371
				},
				"3XL": {
					"printful_variant_id": 5270096372
				}
			},
			"Heather Red": {
				"S": {
					"printful_variant_id": 5270096349
				},
				"M": {
					"printful_variant_id": 5270096350
				},
				"L": {
					"printful_variant_id": 5270096351
				},
				"XL": {
					"printful_variant_id": 5270096352
				},
				"2XL": {
					"printful_variant_id": 5270096353
				},
				"3XL": {
					"printful_variant_id": 5270096354
				}
			},
			"Maroon": {
				"S": {
					"printful_variant_id": 5270096325
				},
				"M": {
					"printful_variant_id": 5270096326
				},
				"L": {
					"printful_variant_id": 5270096327
				},
				"XL": {
					"printful_variant_id": 5270096328
				},
				"2XL": {
					"printful_variant_id": 5270096329
				},
				"3XL": {
					"printful_variant_id": 5270096330
				}
			},
			"Pink": {
				"S": {
					"printful_variant_id": 5270096361
				},
				"M": {
					"printful_variant_id": 5270096362
				},
				"L": {
					"printful_variant_id": 5270096363
				},
				"XL": {
					"printful_variant_id": 5270096364
				},
				"2XL": {
					"printful_variant_id": 5270096365
				},
				"3XL": {
					"printful_variant_id": 5270096366
				}
			},
			"Forest Green": {
				"S": {
					"printful_variant_id": 5270096331
				},
				"M": {
					"printful_variant_id": 5270096332
				},
				"L": {
					"printful_variant_id": 5270096333
				},
				"XL": {
					"printful_variant_id": 5270096334
				},
				"2XL": {
					"printful_variant_id": 5270096335
				},
				"3XL": {
					"printful_variant_id": 5270096336
				}
			},
			"Leaf": {
				"S": {
					"printful_variant_id": 5270096355
				},
				"M": {
					"printful_variant_id": 5270096356
				},
				"L": {
					"printful_variant_id": 5270096357
				},
				"XL": {
					"printful_variant_id": 5270096358
				},
				"2XL": {
					"printful_variant_id": 5270096359
				},
				"3XL": {
					"printful_variant_id": 5270096360
				}
			},
			"Heather Deep Teal": {
				"S": {
					"printful_variant_id": 5270096337
				},
				"M": {
					"printful_variant_id": 5270096338
				},
				"L": {
					"printful_variant_id": 5270096339
				},
				"XL": {
					"printful_variant_id": 5270096340
				},
				"2XL": {
					"printful_variant_id": 5270096341
				},
				"3XL": {
					"printful_variant_id": 5270096342
				}
			},
			"Navy": {
				"S": {
					"printful_variant_id": 5270096313
				},
				"M": {
					"printful_variant_id": 5270096314
				},
				"L": {
					"printful_variant_id": 5270096315
				},
				"XL": {
					"printful_variant_id": 5270096316
				},
				"2XL": {
					"printful_variant_id": 5270096317
				},
				"3XL": {
					"printful_variant_id": 5270096318
				}
			},
			"Heather True Royal": {
				"S": {
					"printful_variant_id": 5270096343
				},
				"M": {
					"printful_variant_id": 5270096344
				},
				"L": {
					"printful_variant_id": 5270096345
				},
				"XL": {
					"printful_variant_id": 5270096346
				},
				"2XL": {
					"printful_variant_id": 5270096347
				},
				"3XL": {
					"printful_variant_id": 5270096348
				}
			},
			"Black": {
				"S": {
					"printful_variant_id": 5270096319
				},
				"M": {
					"printful_variant_id": 5270096320
				},
				"L": {
					"printful_variant_id": 5270096321
				},
				"XL": {
					"printful_variant_id": 5270096322
				},
				"2XL": {
					"printful_variant_id": 5270096323
				},
				"3XL": {
					"printful_variant_id": 5270096324
				}
			}
		}
	},
	"69e056ae13e1c3": {
		"name": "Unisex T-Shirt HMC Crow Front and Back",
		"price": 2000,
		"variants": {
			"White": {
				"XS": {
					"printful_variant_id": 5270096496
				},
				"S": {
					"printful_variant_id": 5270096497
				},
				"M": {
					"printful_variant_id": 5270096498
				},
				"L": {
					"printful_variant_id": 5270096499
				},
				"XL": {
					"printful_variant_id": 5270096500
				},
				"2XL": {
					"printful_variant_id": 5270096501
				}
			},
			"Cardinal": {
				"XS": {
					"printful_variant_id": 5270096463
				},
				"S": {
					"printful_variant_id": 5270096464
				},
				"M": {
					"printful_variant_id": 5270096465
				},
				"L": {
					"printful_variant_id": 5270096466
				},
				"XL": {
					"printful_variant_id": 5270096467
				},
				"2XL": {
					"printful_variant_id": 5270096468
				}
			},
			"Pink": {
				"S": {
					"printful_variant_id": 5270096491
				},
				"M": {
					"printful_variant_id": 5270096492
				},
				"L": {
					"printful_variant_id": 5270096493
				},
				"XL": {
					"printful_variant_id": 5270096494
				},
				"2XL": {
					"printful_variant_id": 5270096495
				}
			},
			"Mustard": {
				"XS": {
					"printful_variant_id": 5270096479
				},
				"S": {
					"printful_variant_id": 5270096480
				},
				"M": {
					"printful_variant_id": 5270096481
				},
				"L": {
					"printful_variant_id": 5270096482
				},
				"XL": {
					"printful_variant_id": 5270096483
				},
				"2XL": {
					"printful_variant_id": 5270096484
				}
			},
			"Forest": {
				"S": {
					"printful_variant_id": 5270096469
				},
				"M": {
					"printful_variant_id": 5270096470
				},
				"L": {
					"printful_variant_id": 5270096471
				},
				"XL": {
					"printful_variant_id": 5270096472
				},
				"2XL": {
					"printful_variant_id": 5270096473
				}
			},
			"Teal": {
				"XS": {
					"printful_variant_id": 5270096485
				},
				"S": {
					"printful_variant_id": 5270096486
				},
				"M": {
					"printful_variant_id": 5270096487
				},
				"L": {
					"printful_variant_id": 5270096488
				},
				"XL": {
					"printful_variant_id": 5270096489
				},
				"2XL": {
					"printful_variant_id": 5270096490
				}
			},
			"Aqua": {
				"S": {
					"printful_variant_id": 5270096474
				},
				"M": {
					"printful_variant_id": 5270096475
				},
				"L": {
					"printful_variant_id": 5270096476
				},
				"XL": {
					"printful_variant_id": 5270096477
				},
				"2XL": {
					"printful_variant_id": 5270096478
				}
			},
			"Navy": {
				"XS": {
					"printful_variant_id": 5270096457
				},
				"S": {
					"printful_variant_id": 5270096458
				},
				"M": {
					"printful_variant_id": 5270096459
				},
				"L": {
					"printful_variant_id": 5270096460
				},
				"XL": {
					"printful_variant_id": 5270096461
				},
				"2XL": {
					"printful_variant_id": 5270096462
				}
			},
			"Vintage Black": {
				"XS": {
					"printful_variant_id": 5270096450
				},
				"S": {
					"printful_variant_id": 5270096452
				},
				"M": {
					"printful_variant_id": 5270096453
				},
				"L": {
					"printful_variant_id": 5270096454
				},
				"XL": {
					"printful_variant_id": 5270096455
				},
				"2XL": {
					"printful_variant_id": 5270096456
				}
			}
		}
	}
};
